### ISSUE TITLE
I can cheat

### ISSUE THREAD

**Issue by androbwebb** [albertocerrone93/sei-project-1#3]
I can beat your game by opening the console and running two lines:

```js
document.querySelectorAll('.bomb').forEach((node) => node.classList.add('flagged'));
document.querySelectorAll('.covered:not(.bomb)').forEach((node) => node.click());
```

**Comment by albertocerrone** [comment]
You genius! 
Thanks for showing me this problem, I'll tackle it ASAP

**Comment by androbwebb** [comment]
You'd be better off not attaching the `bomb` class to the element, and instead keeping the list of bomb locations in javascript. Then upon click checking if that space was a bomb.
